import InfoIcon from '../svgs/info.svg';
import MailIcon from '../svgs/mail.svg';
import LeftIcon from '../svgs/leftArrow.svg';
import EyeOpenIcon from '../svgs/eye_open.svg';
import MedicineIcon from '../svgs/medicine.svg';
import RefreshIcon from '../svgs/refreshIcon.svg';
import ChevronRight from '../svgs/chevron-right.svg';
import SearchIcon from '../svgs/searchIcon.svg';
import CloseIcon from '../svgs/closeIcon.svg';
export { MailIcon, EyeOpenIcon, LeftIcon, RefreshIcon, ChevronRight, InfoIcon, MedicineIcon, SearchIcon, CloseIcon };
